# Generated by Django 3.2 on 2023-03-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('handled', 'Handled')], default='unread', max_length=10),
        ),
    ]
