# Generated by Django 3.2 on 2023-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230307_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wheight',
            field=models.CharField(max_length=254),
        ),
    ]
