# Generated by Django 3.2 on 2023-03-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_wheight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wheight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
